### ISSUE TITLE
dataset.py: demographics function - Better data structure ? (& remove print)

### ISSUE THREAD

**Issue by leriomaggio** [landiisotta/behavioral_phenotyping#2]
All the `print` functions should be removed and not used inside functions.

If you'd need some logging information to keep track during the execution of specific function(s), you could rather use the Python `logging` module (https://docs.python.org/3/library/logging.html)

As for the specific case, namely `dataset.demographics`, my suggestion would be to collect all the information of interest in a suitable data structure (e.g. `pandas.DataFrame`?) and return them for later use.

This is mainly because functions should not have any possible side-effect when executed, and printing is definitely an unexpected behaviour

**Note:**
Changes here will require an update of the `phenotyping_stratification_pipeline` notebook.

**Comment by leriomaggio** [comment]
Renamed Issue for better logging.

**Comment by leriomaggio** [comment]
The removal of `print` function review&removal also applies to the `clustering` module.

**Comment by landiisotta** [comment]
I have added the function ```cohort_info```, as I stated in the reply to Issue #3, in order to separate the need for descriptive statistics and csv files from the rest. 

Now the function:
* Creates a dictionary of dataclass ```Pinfo``` instances;
* Calls a private function to save the info to csv files (namely, ```_dump_info```);
* Leverages the attribute ```compute``` of the class ```DataStatistics``` in module ```basic_statistics``` to save to a log file the basic data statistics. 

I know you said it is probably better to compute the statistics at a different time, but I prefer to have the right statistics right away every time I access the dataframe. BUT, looking on the bright side I used the ```logging``` module as you suggested! :) I used it also in ```dataset``` module to keep track of what it's doing.
