### ISSUE TITLE
features.py: Encapsulation Required

### ISSUE THREAD

**Issue by leriomaggio** [landiisotta/behavioral_phenotyping#4]
The `create_tokens` function in `features.py` is really difficult to comprehend, plus it looks it has lots of slightly duplicated code (_code clones_, as I used to call'em when I was a PhD student :-) 

Instead of writing this huge and un-maintainable functions, I would rather go for creating a class with specialised methods.

I don't quite get the meaning of all the matches in that long list of `if-clauses`, but perhaps you can better reorganise them.

The starting point in my opinion would be the `df_dict` structure. And the, the return type. 

Perhaps the dictionary here is too flexible and general that requires all these checking.

As a reference, I would suggest to take a quick look here: https://dzone.com/articles/code-smells-if-statements

**Comment by leriomaggio** [comment]
The same would apply to other functions in the module, namely `behr_levelX`

**Comment by landiisotta** [comment]
I have completely rethought of the ```features.py``` module. Given that each set of instruments for the behavioral evaluation of a condition entails a different feature set (to build both the vocabulary for behavioral embedding and the quantitative dataset) it is probably better to include directly in the database a datamap table which maps each instrument to the boolean vector of the features for the desired level. 
This is not yet implemented in the database, but I have written the ```datamap.py``` module, with the ```connect_api``` method that will be integrated in the script that builds it. The method connects directly to Google Sheet API and returns a dataframe. For now, I will use it as a private method in the pipeline. The only messy thing is the dictionary in ```utils.py``` that will allow to build the datamap. However, the features module gained in readability and efficiency (I hope :)). 
Specifically, the new ```features.py``` is now a class with attributes that, leveraging the datamap, builds the behavioral EHRs and vocabulary for a specific level with instance method ```create_level_tokens()``` and a quantitative features dataframe for level 4 with ```create_level_features()```. 
PS. also the ```__create_token``` ```staticmethod``` is a bit messy, in that it is tailored to the ODF database, however, it is easily changeable because I isolated it.
